[workspace]
members = []

[package]
authors = ["Kazuhisa TAKEI <kazuhisa@gmail.com>"]
description = "Nushell dataframe plugin commands based on polars."
edition = "2024"
rust-version = "1.95.0"
license = "MIT"
name = "nu_plugin_polars_dyn"
repository = "https://github.com/kazu/nu_plugin_polars_dyn"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "nu_plugin_polars_dyn"
bench = false

[lib]
name = "nu_plugin_polars"
bench = false

[dependencies]
nu-protocol = "=0.114.1"
nu-plugin = { version = "=0.114.1", default-features = false }
nu-path = "=0.114.1"

# Potential dependencies for extras
chrono = { version = "0.4.42", features = [
  "unstable-locales",
], default-features = false }
chrono-tz = "0.10"
fancy-regex = "0.18"
indexmap = { version = "2.13" }
num = { version = "0.4" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.151"
sqlparser = { version = "~0.61.0" }
polars-io = { version = "~0.55.2", features = ["avro", "cloud", "aws", "azure", "gcp"] }
polars-arrow = { version = "~0.55.2" }
polars-ops = { version = "~0.55.2", features = ["pivot", "cutqcut"] }
polars-plan = { version = "~0.55.2", features = ["regex"] }
polars-utils = { version = "~0.55.2" }
polars-lazy = { version = "~0.55.2", features = ["ffi_plugin"] }
polars-compute = { version = "~0.55.2" }
polars-core = { version = "~0.55.2" }
planus = { version = "~1.1.1" } # Temporarily here to convince cargo not to upgrade planus to 1.2.0
typetag = "0.2"
env_logger = "0.11.8"
log = "0.4"
uuid = { version = "1.23", features = ["v4", "serde"] }

# Do to a compile error with polars, this included to force the raw dependency
hashbrown = { version = "0.17", features = ["rayon", "serde"] }

[dependencies.polars]
features = [
  "abs",
  "arg_where",
  "bigidx",
  "bitwise",
  "checked_arithmetic",
  "cloud",
  "concat_str",
  "cross_join",
  "iejoin",
  "csv",
  "cum_agg",
  "default",
  "dtype-categorical",
  "dtype-datetime",
  "dtype-struct",
  "dtype-decimal",
  "dtype-i8",
  "dtype-i16",
  "dtype-u8",
  "dtype-u16",
  "dtype-u128",
  "dynamic_group_by",
  "ipc",
  "is_in",
  "json",
  "lazy",
  "log",
  "object",
  "parquet",
  "pivot",
  "random",
  "replace",
  "rolling_window",
  "rows",
  "round_series",
  "serde",
  "serde-lazy",
  "sign",
  "strings",
  "string_to_integer",
  "timezones",
  "temporal",
  "to_dummies",
  "trigonometry",
]
optional = false
version = "=0.55.2"

[dev-dependencies]
nu-cmd-lang = { version = "=0.114.1", features = ["plugin"] }
nu-engine = { version = "=0.114.1", features = ["plugin"] }
nu-parser = { version = "=0.114.1", features = ["plugin"] }
nu-command = { version = "=0.114.1", features = ["plugin"] }
nu-plugin-test-support = "=0.114.1"

tempfile = "3.27"

[lints.clippy]
format_push_string = "warn"
needless_raw_strings = "allow"
result_large_err = "allow"
unchecked_time_subtraction = "warn"
unwrap_used = "deny"
used_underscore_binding = "warn"
